# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesktopCalculatorGUI_1.06.00.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QDialog, QPushButton, QVBoxLayout, QApplication, QMessageBox, QMainWindow
from PyQt5.QtGui import*
from PyQt5.QtCore import*


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 331, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.calculatorPage = QtWidgets.QWidget()
        self.calculatorPage.setObjectName("calculatorPage")
        self.button_8 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_8.setGeometry(QtCore.QRect(100, 250, 71, 41))
        self.button_8.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_8.setAutoDefault(True)
        self.button_8.setDefault(False)
        self.button_8.setFlat(True)
        self.button_8.setObjectName("button_8")
        self.button_equals = QtWidgets.QPushButton(self.calculatorPage)
        self.button_equals.setGeometry(QtCore.QRect(260, 350, 51, 91))
        self.button_equals.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 139, 85);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(230, 125, 76);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(217, 118, 72);\n"
"}\n"
"\n"
"")
        self.button_equals.setAutoDefault(True)
        self.button_equals.setDefault(False)
        self.button_equals.setFlat(True)
        self.button_equals.setObjectName("button_equals")
        self.button_dot = QtWidgets.QPushButton(self.calculatorPage)
        self.button_dot.setGeometry(QtCore.QRect(180, 400, 71, 41))
        self.button_dot.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_dot.setAutoDefault(True)
        self.button_dot.setDefault(False)
        self.button_dot.setFlat(True)
        self.button_dot.setObjectName("button_dot")
        self.button_6 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_6.setGeometry(QtCore.QRect(180, 300, 71, 41))
        self.button_6.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_6.setAutoDefault(True)
        self.button_6.setDefault(False)
        self.button_6.setFlat(True)
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_7.setGeometry(QtCore.QRect(20, 250, 71, 41))
        self.button_7.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_7.setAutoDefault(True)
        self.button_7.setDefault(False)
        self.button_7.setFlat(True)
        self.button_7.setObjectName("button_7")
        self.button_backspace = QtWidgets.QPushButton(self.calculatorPage)
        self.button_backspace.setGeometry(QtCore.QRect(180, 150, 71, 41))
        self.button_backspace.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 19pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}\n"
"\n"
"")
        self.button_backspace.setAutoDefault(True)
        self.button_backspace.setDefault(False)
        self.button_backspace.setFlat(True)
        self.button_backspace.setObjectName("button_backspace")
        self.button_closePar = QtWidgets.QPushButton(self.calculatorPage)
        self.button_closePar.setGeometry(QtCore.QRect(100, 150, 71, 41))
        self.button_closePar.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 18pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.button_closePar.setAutoDefault(True)
        self.button_closePar.setDefault(False)
        self.button_closePar.setFlat(True)
        self.button_closePar.setObjectName("button_closePar")
        self.button_clear = QtWidgets.QPushButton(self.calculatorPage)
        self.button_clear.setGeometry(QtCore.QRect(180, 200, 71, 41))
        self.button_clear.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 16pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_clear.setAutoDefault(True)
        self.button_clear.setDefault(False)
        self.button_clear.setFlat(True)
        self.button_clear.setObjectName("button_clear")
        self.button_3 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_3.setGeometry(QtCore.QRect(180, 350, 71, 41))
        self.button_3.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_3.setAutoDefault(True)
        self.button_3.setDefault(False)
        self.button_3.setFlat(True)
        self.button_3.setObjectName("button_3")
        self.button_9 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_9.setGeometry(QtCore.QRect(180, 250, 71, 41))
        self.button_9.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_9.setAutoDefault(True)
        self.button_9.setDefault(False)
        self.button_9.setFlat(True)
        self.button_9.setObjectName("button_9")
        self.button_4 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_4.setGeometry(QtCore.QRect(20, 300, 71, 41))
        self.button_4.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_4.setAutoDefault(True)
        self.button_4.setDefault(False)
        self.button_4.setFlat(True)
        self.button_4.setObjectName("button_4")
        self.button_minus = QtWidgets.QPushButton(self.calculatorPage)
        self.button_minus.setGeometry(QtCore.QRect(260, 250, 51, 41))
        self.button_minus.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(217, 231, 245);\n"
"font: 20pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(201, 213, 226);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(187, 199, 211);\n"
"}\n"
"\n"
"")
        self.button_minus.setAutoDefault(True)
        self.button_minus.setDefault(False)
        self.button_minus.setFlat(True)
        self.button_minus.setObjectName("button_minus")
        self.settingsButton = QtWidgets.QPushButton(self.calculatorPage)
        self.settingsButton.setGeometry(QtCore.QRect(120, 450, 75, 21))
        self.settingsButton.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"color: rgb(255,255,255);\n"
"border-radius : 8px; \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/icons8-settings-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon)
        self.settingsButton.setIconSize(QtCore.QSize(10, 10))
        self.settingsButton.setObjectName("settingsButton")
        self.resultOutput = QtWidgets.QLabel(self.calculatorPage)
        self.resultOutput.setGeometry(QtCore.QRect(20, 80, 271, 31))
        self.resultOutput.setStyleSheet("font: 23pt \"calibri\";\n"
"color: rgb(94, 94, 94);")
        self.resultOutput.setText("")
        self.resultOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.resultOutput.setObjectName("resultOutput")
        self.screenOutput = QtWidgets.QLineEdit(self.calculatorPage)
        self.screenOutput.setGeometry(QtCore.QRect(20, 40, 291, 20))
        self.screenOutput.setStyleSheet("border: none; background: transparent;\n"
"font: 12pt MS Shell Dlg 2;\n"
"color: rgb(190, 190, 190);")
        self.screenOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.screenOutput.setObjectName("screenOutput")
        self.button_mult = QtWidgets.QPushButton(self.calculatorPage)
        self.button_mult.setGeometry(QtCore.QRect(260, 200, 51, 41))
        self.button_mult.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(217, 231, 245);\n"
"font: 20pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(201, 213, 226);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(187, 199, 211);\n"
"}\n"
"\n"
"")
        self.button_mult.setAutoDefault(True)
        self.button_mult.setDefault(False)
        self.button_mult.setFlat(True)
        self.button_mult.setObjectName("button_mult")
        self.button_5 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_5.setGeometry(QtCore.QRect(100, 300, 71, 41))
        self.button_5.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_5.setAutoDefault(True)
        self.button_5.setDefault(False)
        self.button_5.setFlat(True)
        self.button_5.setObjectName("button_5")
        self.button_0 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_0.setGeometry(QtCore.QRect(20, 400, 151, 41))
        self.button_0.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_0.setAutoDefault(True)
        self.button_0.setDefault(False)
        self.button_0.setFlat(True)
        self.button_0.setObjectName("button_0")
        self.button_2 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_2.setGeometry(QtCore.QRect(100, 350, 71, 41))
        self.button_2.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_2.setAutoDefault(True)
        self.button_2.setDefault(False)
        self.button_2.setFlat(True)
        self.button_2.setObjectName("button_2")
        self.button_openPar = QtWidgets.QPushButton(self.calculatorPage)
        self.button_openPar.setGeometry(QtCore.QRect(20, 150, 71, 41))
        self.button_openPar.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 18pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.button_openPar.setAutoDefault(True)
        self.button_openPar.setDefault(False)
        self.button_openPar.setFlat(True)
        self.button_openPar.setObjectName("button_openPar")
        self.releaseLabel = QtWidgets.QLabel(self.calculatorPage)
        self.releaseLabel.setGeometry(QtCore.QRect(2, 465, 81, 16))
        self.releaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.releaseLabel.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: rgb(197, 197, 197);")
        self.releaseLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.releaseLabel.setObjectName("releaseLabel")
        self.button_1 = QtWidgets.QPushButton(self.calculatorPage)
        self.button_1.setGeometry(QtCore.QRect(20, 350, 71, 41))
        self.button_1.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_1.setAutoDefault(True)
        self.button_1.setDefault(False)
        self.button_1.setFlat(True)
        self.button_1.setObjectName("button_1")
        self.button_div = QtWidgets.QPushButton(self.calculatorPage)
        self.button_div.setGeometry(QtCore.QRect(260, 150, 51, 41))
        self.button_div.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(217, 231, 245);\n"
"font: 20pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(201, 213, 226);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(187, 199, 211);\n"
"}\n"
"\n"
"")
        self.button_div.setAutoDefault(True)
        self.button_div.setDefault(False)
        self.button_div.setFlat(True)
        self.button_div.setObjectName("button_div")
        self.button_plus = QtWidgets.QPushButton(self.calculatorPage)
        self.button_plus.setGeometry(QtCore.QRect(260, 300, 51, 41))
        self.button_plus.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(217, 231, 245);\n"
"font: 20pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(201, 213, 226);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(187, 199, 211);\n"
"}\n"
"\n"
"")
        self.button_plus.setAutoDefault(True)
        self.button_plus.setDefault(False)
        self.button_plus.setFlat(True)
        self.button_plus.setObjectName("button_plus")
        self.decimalResultOutput = QtWidgets.QLabel(self.calculatorPage)
        self.decimalResultOutput.setGeometry(QtCore.QRect(20, 110, 271, 31))
        self.decimalResultOutput.setStyleSheet("border: none; background: transparent;\n"
"font: 11pt calibri;\n"
"color: rgb(150, 150, 150);")
        self.decimalResultOutput.setText("")
        self.decimalResultOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.decimalResultOutput.setObjectName("decimalResultOutput")
        self.redoButton = QtWidgets.QPushButton(self.calculatorPage)
        self.redoButton.setGeometry(QtCore.QRect(198, 450, 21, 21))
        self.redoButton.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"color: rgb(255,255,255);\n"
"border-radius : 8px; \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}\n"
"\n"
"")
        self.redoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/redo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoButton.setIcon(icon1)
        self.redoButton.setIconSize(QtCore.QSize(10, 10))
        self.redoButton.setObjectName("redoButton")
        self.undoButton = QtWidgets.QPushButton(self.calculatorPage)
        self.undoButton.setGeometry(QtCore.QRect(96, 450, 21, 21))
        self.undoButton.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"color: rgb(255,255,255);\n"
"border-radius : 8px; \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}\n"
"\n"
"")
        self.undoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/undo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon2)
        self.undoButton.setIconSize(QtCore.QSize(10, 10))
        self.undoButton.setObjectName("undoButton")
        self.button_percent = QtWidgets.QPushButton(self.calculatorPage)
        self.button_percent.setGeometry(QtCore.QRect(20, 200, 71, 41))
        self.button_percent.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 20pt \"calibri\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_percent.setAutoDefault(True)
        self.button_percent.setDefault(False)
        self.button_percent.setFlat(True)
        self.button_percent.setObjectName("button_percent")
        self.button_ans = QtWidgets.QPushButton(self.calculatorPage)
        self.button_ans.setGeometry(QtCore.QRect(100, 200, 71, 41))
        self.button_ans.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 16pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(212, 212, 212);\n"
"}\n"
"\n"
"")
        self.button_ans.setAutoDefault(True)
        self.button_ans.setDefault(False)
        self.button_ans.setFlat(True)
        self.button_ans.setObjectName("button_ans")
        self.stackedWidget.addWidget(self.calculatorPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.decimalPoints_slider = QtWidgets.QSlider(self.settingsPage)
        self.decimalPoints_slider.setEnabled(True)
        self.decimalPoints_slider.setGeometry(QtCore.QRect(90, 230, 141, 21))
        self.decimalPoints_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border-radius: 1px;\n"
"    height: 3px;\n"
"    margin: 0px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    margin: -7px 0;\n"
"    border-radius: 8px;\n"
"    padding: -7px 0px;\n"
"}"
"QSlider::handle:disabled {\n"
"    background-color: rgb(170, 170, 170);\n"
"}")
        self.decimalPoints_slider.setMinimum(1)
        self.decimalPoints_slider.setMaximum(11)
        self.decimalPoints_slider.setPageStep(1)
        self.decimalPoints_slider.setSliderPosition(6)
        self.decimalPoints_slider.setOrientation(QtCore.Qt.Horizontal)
        self.decimalPoints_slider.setInvertedAppearance(False)
        self.decimalPoints_slider.setInvertedControls(False)
        self.decimalPoints_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.decimalPoints_slider.setTickInterval(1)
        self.decimalPoints_slider.setObjectName("decimalPoints_slider")
        self.clipboard_checkbox = QtWidgets.QCheckBox(self.settingsPage)
        self.clipboard_checkbox.setGeometry(QtCore.QRect(190, 180, 101, 20))
        self.clipboard_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.clipboard_checkbox.setStyleSheet("QCheckBox \n"
"{ \n"
"    font: 10pt \"Arial\";\n"
"    font-weight: 400;\n"
"}\n"
"QCheckBox::indicator\n"
"{\n"
"    width : 40px;\n"
"    height : 40px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked \n"
"{\n"
"    border-image: url(icons/toggle-off.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked \n"
"{\n"
"    border-image: url(icons/toggle-on.png);\n"
"}")
        self.clipboard_checkbox.setObjectName("clipboard_checkbox")
        self.decimalPoints_label = QtWidgets.QLabel(self.settingsPage)
        self.decimalPoints_label.setGeometry(QtCore.QRect(70, 209, 201, 21))
        self.decimalPoints_label.setStyleSheet("font: 10pt \"Arial\";\n"
"font-weight: 400;")
        self.decimalPoints_label.setObjectName("decimalPoints_label")
        self.discard_button = QtWidgets.QPushButton(self.settingsPage)
        self.discard_button.setGeometry(QtCore.QRect(90, 400, 71, 31))
        self.discard_button.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.discard_button.setAutoDefault(True)
        self.discard_button.setDefault(False)
        self.discard_button.setFlat(True)
        self.discard_button.setObjectName("discard_button")
        self.save_button = QtWidgets.QPushButton(self.settingsPage)
        self.save_button.setGeometry(QtCore.QRect(170, 400, 71, 31))
        self.save_button.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.save_button.setAutoDefault(True)
        self.save_button.setDefault(False)
        self.save_button.setFlat(True)
        self.save_button.setObjectName("save_button")
        self.clipboardDecimalPointDisplay = QtWidgets.QLabel(self.settingsPage)
        self.clipboardDecimalPointDisplay.setGeometry(QtCore.QRect(240, 230, 16, 16))
        self.clipboardDecimalPointDisplay.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(255,255,255);\n"
"border-radius: 3px;\n"
"}")
        self.clipboardDecimalPointDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.clipboardDecimalPointDisplay.setObjectName("clipboardDecimalPointDisplay")
        self.reportLinkLabel = QtWidgets.QLabel(self.settingsPage)
        self.reportLinkLabel.setGeometry(QtCore.QRect(120, 440, 91, 31))
        self.reportLinkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.reportLinkLabel.setWordWrap(False)
        self.reportLinkLabel.setOpenExternalLinks(True)
        self.reportLinkLabel.setObjectName("reportLinkLabel")
        self.zoomSettingsLabel = QtWidgets.QLabel(self.settingsPage)
        self.zoomSettingsLabel.setGeometry(QtCore.QRect(50, 40, 91, 31))
        self.zoomSettingsLabel.setStyleSheet("QLabel\n"
"{\n"
"font: 12pt \"Arial rounded mt bold\";\n"
"}\n"
"")
        self.zoomSettingsLabel.setObjectName("zoomSettingsLabel")
        self.releaseLabel_2 = QtWidgets.QLabel(self.settingsPage)
        self.releaseLabel_2.setGeometry(QtCore.QRect(10, 460, 81, 16))
        self.releaseLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.releaseLabel_2.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: rgb(197, 197, 197);")
        self.releaseLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.releaseLabel_2.setObjectName("releaseLabel_2")
        self.backgroundbox_zoom = QtWidgets.QLabel(self.settingsPage)
        self.backgroundbox_zoom.setGeometry(QtCore.QRect(-10, 40, 321, 101))
        self.backgroundbox_zoom.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(255,255,255);\n"
"border-radius: 6px;\n"
"}")
        self.backgroundbox_zoom.setText("")
        self.backgroundbox_zoom.setObjectName("backgroundbox_zoom")
        self.backgroundbox_clipboard = QtWidgets.QLabel(self.settingsPage)
        self.backgroundbox_clipboard.setGeometry(QtCore.QRect(-10, 150, 321, 111))
        self.backgroundbox_clipboard.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(255,255,255);\n"
"border-radius: 6px;\n"
"}")
        self.backgroundbox_clipboard.setText("")
        self.backgroundbox_clipboard.setObjectName("backgroundbox_clipboard")
        self.clipboardSettingsLabel = QtWidgets.QLabel(self.settingsPage)
        self.clipboardSettingsLabel.setGeometry(QtCore.QRect(50, 150, 81, 31))
        self.clipboardSettingsLabel.setStyleSheet("QLabel\n"
"{\n"
"font: 12pt \"Arial rounded mt bold\";\n"
"}\n"
"")
        self.clipboardSettingsLabel.setObjectName("clipboardSettingsLabel")
        self.resultSettingsLabel = QtWidgets.QLabel(self.settingsPage)
        self.resultSettingsLabel.setGeometry(QtCore.QRect(50, 270, 61, 31))
        self.resultSettingsLabel.setStyleSheet("QLabel\n"
"{\n"
"font: 12pt \"Arial rounded mt bold\";\n"
"}\n"
"")
        self.resultSettingsLabel.setObjectName("resultSettingsLabel")
        self.backgroundbox_result = QtWidgets.QLabel(self.settingsPage)
        self.backgroundbox_result.setGeometry(QtCore.QRect(-10, 270, 321, 91))
        self.backgroundbox_result.setStyleSheet("QLabel\n"
"{\n"
"background-color: rgb(255,255,255);\n"
"border-radius: 6px;\n"
"}")
        self.backgroundbox_result.setText("")
        self.backgroundbox_result.setObjectName("backgroundbox_result")
        self.settinginfo_result = QtWidgets.QLabel(self.settingsPage)
        self.settinginfo_result.setEnabled(True)
        self.settinginfo_result.setGeometry(QtCore.QRect(50, 300, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settinginfo_result.setFont(font)
        self.settinginfo_result.setStyleSheet("color: Gray;\n"
"font: 9pt \"Arial\";\n"
"font-weight: 400;")
        self.settinginfo_result.setObjectName("settinginfo_result")
        self.display_fraction_radio_button = QtWidgets.QRadioButton(self.settingsPage)
        self.display_fraction_radio_button.setGeometry(QtCore.QRect(60, 330, 83, 18))
        self.display_fraction_radio_button.setStyleSheet("font: 10pt \"Arial\";\n"
"font-weight: 400;")
        self.display_fraction_radio_button.setObjectName("display_fraction_radio_button")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.display_fraction_radio_button)
        self.display_decimal_radio_button = QtWidgets.QRadioButton(self.settingsPage)
        self.display_decimal_radio_button.setGeometry(QtCore.QRect(140, 330, 83, 18))
        self.display_decimal_radio_button.setStyleSheet("font: 10pt \"Arial\";\n"
"font-weight: 400;")
        self.display_decimal_radio_button.setObjectName("display_decimal_radio_button")
        self.buttonGroup_2.addButton(self.display_decimal_radio_button)
        self.settinginfo_clipboard = QtWidgets.QLabel(self.settingsPage)
        self.settinginfo_clipboard.setEnabled(True)
        self.settinginfo_clipboard.setGeometry(QtCore.QRect(50, 180, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settinginfo_clipboard.setFont(font)
        self.settinginfo_clipboard.setStyleSheet("color: Gray;\n"
"font: 9pt \"Arial\";\n"
"font-weight: 400;")
        self.settinginfo_clipboard.setObjectName("settinginfo_clipboard")
        self.icon_clipboard = QtWidgets.QLabel(self.settingsPage)
        self.icon_clipboard.setGeometry(QtCore.QRect(10, 190, 21, 21))
        self.icon_clipboard.setStyleSheet("border-image: url(icons/copy.png);\n"
"width : 40px;\n"
"height : 40px;")
        self.icon_clipboard.setText("")
        self.icon_clipboard.setObjectName("icon_clipboard")
        self.icon_result = QtWidgets.QLabel(self.settingsPage)
        self.icon_result.setGeometry(QtCore.QRect(10, 300, 21, 21))
        self.icon_result.setStyleSheet("border-image: url(icons/monitor.png);\n"
"width : 40px;\n"
"height : 40px;")
        self.icon_result.setText("")
        self.icon_result.setObjectName("icon_result")
        self.icon_zoom = QtWidgets.QLabel(self.settingsPage)
        self.icon_zoom.setGeometry(QtCore.QRect(10, 80, 21, 21))
        self.icon_zoom.setStyleSheet("border-image: url(icons/scale.png);\n"
"width : 40px;\n"
"height : 40px;")
        self.icon_zoom.setText("")
        self.icon_zoom.setObjectName("icon_zoom")
        self.zoom_comboBox = QtWidgets.QComboBox(self.settingsPage)
        self.zoom_comboBox.setGeometry(QtCore.QRect(50, 100, 106, 31))
        self.zoom_comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    min-width: 6em;\n"
"    font: 10pt \"Arial\";\n"
"    font-weight: 400;\n"
"    padding: 4px 4px 4px 7px\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    width : 10px;\n"
"    height : 10px;\n"
"    image: url(icons/down-arrow.png);\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: white;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px;\n"
"    outline: none;\n"
"    selection-background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    min-height: 50px;\n"
"}")
        self.zoom_comboBox.setObjectName("zoom_comboBox")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.settinginfo_clipboard_2 = QtWidgets.QLabel(self.settingsPage)
        self.settinginfo_clipboard_2.setEnabled(True)
        self.settinginfo_clipboard_2.setGeometry(QtCore.QRect(50, 70, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settinginfo_clipboard_2.setFont(font)
        self.settinginfo_clipboard_2.setStyleSheet("color: Gray;\n"
"font: 9pt \"Arial\";\n"
"font-weight: 400;")
        self.settinginfo_clipboard_2.setObjectName("settinginfo_clipboard_2")
        self.label = QtWidgets.QLabel(self.settingsPage)
        self.label.setGeometry(QtCore.QRect(0, 40, 41, 101))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"background-color: skyblue;\n"
"\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.settingsPage)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 41, 111))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"background-color: skyblue;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.settingsPage)
        self.label_3.setGeometry(QtCore.QRect(0, 270, 41, 91))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"background-color: skyblue;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.backgroundbox_clipboard.raise_()
        self.label_2.raise_()
        self.backgroundbox_result.raise_()
        self.label_3.raise_()
        self.backgroundbox_zoom.raise_()
        self.label.raise_()
        self.decimalPoints_slider.raise_()
        self.clipboard_checkbox.raise_()
        self.decimalPoints_label.raise_()
        self.discard_button.raise_()
        self.save_button.raise_()
        self.clipboardDecimalPointDisplay.raise_()
        self.reportLinkLabel.raise_()
        self.zoomSettingsLabel.raise_()
        self.releaseLabel_2.raise_()
        self.clipboardSettingsLabel.raise_()
        self.resultSettingsLabel.raise_()
        self.settinginfo_result.raise_()
        self.display_fraction_radio_button.raise_()
        self.display_decimal_radio_button.raise_()
        self.settinginfo_clipboard.raise_()
        self.icon_clipboard.raise_()
        self.icon_result.raise_()
        self.icon_zoom.raise_()
        self.zoom_comboBox.raise_()
        self.settinginfo_clipboard_2.raise_()
        self.stackedWidget.addWidget(self.settingsPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " Sagy Calculator"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_equals.setText(_translate("MainWindow", "="))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_backspace.setText(_translate("MainWindow", "⌫"))
        self.button_closePar.setText(_translate("MainWindow", ")"))
        self.button_clear.setText(_translate("MainWindow", "AC"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.screenOutput.setText(_translate("MainWindow", "Enter Your Equation"))
        self.button_mult.setText(_translate("MainWindow", "×"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_openPar.setText(_translate("MainWindow", "("))
        self.releaseLabel.setText(_translate("MainWindow", "  YitzchakMeltz Release_2.00.00"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_div.setText(_translate("MainWindow", "÷"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_percent.setText(_translate("MainWindow", "%"))
        self.button_ans.setText(_translate("MainWindow", "ANS"))
        self.clipboard_checkbox.setText(_translate("MainWindow", "Disabled"))
        self.decimalPoints_label.setText(_translate("MainWindow", "Decimal points to copy to clipboard"))
        self.discard_button.setText(_translate("MainWindow", "Cancel"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.clipboardDecimalPointDisplay.setText(_translate("MainWindow", "6"))
        self.reportLinkLabel.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://sassyowl.herokuapp.com/support.html\"><span style=\" color:#0000ff;\">report a problem</span></a></p></body></html>"))
        self.zoomSettingsLabel.setText(_translate("MainWindow", "Zoom"))
        self.releaseLabel_2.setText(_translate("MainWindow", "  YitzchakMeltz Release_2.00.00"))
        self.clipboardSettingsLabel.setText(_translate("MainWindow", "Clipboard"))
        self.resultSettingsLabel.setText(_translate("MainWindow", "Display"))
        self.settinginfo_result.setText(_translate("MainWindow", "Choose the format of your primary result"))
        self.display_fraction_radio_button.setText(_translate("MainWindow", "Fraction"))
        self.display_decimal_radio_button.setText(_translate("MainWindow", "Decimal"))
        self.settinginfo_clipboard.setText(_translate("MainWindow", "Copy result to clipboard"))
        self.zoom_comboBox.setItemText(0, _translate("MainWindow", "Auto"))
        self.zoom_comboBox.setItemText(1, _translate("MainWindow", "150%"))
        self.zoom_comboBox.setItemText(2, _translate("MainWindow", "120%"))
        self.zoom_comboBox.setItemText(3, _translate("MainWindow", "100%"))
        self.zoom_comboBox.setItemText(4, _translate("MainWindow", "80%"))
        self.zoom_comboBox.setItemText(5, _translate("MainWindow", "50%"))
        self.settinginfo_clipboard_2.setText(_translate("MainWindow", "Scale the app to a comfortable size"))

