# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\hmeltz\Documents\GitHub\DesktopCalculator\ui\SettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 418)
        self.centralwidget = mainwidget3(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_openPar = QtWidgets.QPushButton(self.centralwidget)
        self.button_openPar.setGeometry(QtCore.QRect(170, 330, 71, 31))
        self.button_openPar.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.button_openPar.setAutoDefault(True)
        self.button_openPar.setDefault(False)
        self.button_openPar.setFlat(True)
        self.button_openPar.setObjectName("button_openPar")
        self.releaseLabel = QtWidgets.QLabel(self.centralwidget)
        self.releaseLabel.setGeometry(QtCore.QRect(10, 400, 161, 16))
        self.releaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.releaseLabel.setStyleSheet("font: 4pt \"MS Shell Dlg 2\";\n"
"color: rgb(197, 197, 197);")
        self.releaseLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.releaseLabel.setObjectName("releaseLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 130, 181, 16))
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(90, 150, 171, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 71, 20))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"font-size: 16px;\n"
"color: rgb(180,180,180);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.button_openPar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_openPar_2.setGeometry(QtCore.QRect(90, 330, 71, 31))
        self.button_openPar_2.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"background-color: rgb(232, 232, 232);\n"
"font: 8pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(211, 211, 211);\n"
"}")
        self.button_openPar_2.setAutoDefault(True)
        self.button_openPar_2.setDefault(False)
        self.button_openPar_2.setFlat(True)
        self.button_openPar_2.setObjectName("button_openPar_2")
        self.scaling_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.scaling_checkbox.setGeometry(QtCore.QRect(70, 70, 191, 18))
        self.scaling_checkbox.setObjectName("scaling_checkbox")
        self.clipboard_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.clipboard_checkbox.setGeometry(QtCore.QRect(70, 100, 171, 18))
        self.clipboard_checkbox.setObjectName("clipboard_checkbox")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_openPar.setText(_translate("MainWindow", "Save"))
        self.releaseLabel.setText(_translate("MainWindow", "  YitzchakMeltz   Release_1.6.0"))
        self.label.setText(_translate("MainWindow", "Decimal points to copy to clipboard"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.button_openPar_2.setText(_translate("MainWindow", "Discard"))
        self.scaling_checkbox.setText(_translate("MainWindow", "Handle high resolution displays"))
        self.clipboard_checkbox.setText(_translate("MainWindow", "Copy answer to clipboard"))
from QWidget import mainwidget3
